version: "3"
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: test_database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            TZ: "Asia/Tokyo"
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql/init:/docker-entrypoint-initdb.d
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
